version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "ch-sdk-node"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
