version: "3.8"

services:
  ingress-proxy:
    container_name: dissolution-ingress-proxy
    image: traefik:v2.2
    command: --api.insecure=true --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
    networks:
      - chs-dev
    ports:
      - 80:80
      - 8080:8080 # Web UI (enabled by --api.insecure=true)
  dissolution-web:
    build: .
    container_name: dissolution-web
    image: dissolution-web:1.0
    labels:
      - traefik.http.routers.dissolution-web.rule=Host(`chs-dev`) && PathPrefix(`/close-a-company/`)
    ports:
      - 3000:3000
    networks:
      - chs-dev
    working_dir: /app
    environment:
      - CDN_HOST=cdn.chs-dev
      - CACHE_SERVER=redis
      - CACHE_DB=0
      - CACHE_PASSWORD=''
      - COOKIE_NAME=SID
      - COOKIE_DOMAIN=chs-dev
      - COOKIE_SECURE_ONLY=0
      - COOKIE_SECRET=ChGovUk-XQrbf3sLj2abFxIY2TlapsJ
      - DEFAULT_SESSION_EXPIRATION=3600
    depends_on:
      - mongo
      - cdn-ch-gov-uk
      - account-ch-gov-uk
      - ch-gov-uk
      - chs-company-profile-api
  # Integrations
  cdn-ch-gov-uk:
    container_name: cdn-ch-gov-uk
    image: 169942020521.dkr.ecr.eu-west-1.amazonaws.com/local/cdn.ch.gov.uk:latest
    labels:
      - traefik.http.routers.cdn-ch-gov-uk.rule=Host(`cdn.chs-dev`)
    networks:
      - chs-dev
    expose:
      - 80
  account-ch-gov-uk:
    container_name: account-ch-gov-uk
    image: 169942020521.dkr.ecr.eu-west-1.amazonaws.com/local/account.ch.gov.uk:latest
    labels:
      - traefik.http.routers.account-ch-gov-uk.rule=Host(`account.chs-dev`)
    environment:
      - ACCOUNT_CH_CLIENT_ID=1234567890.apps.ch.gov.uk
      - ACCOUNT_CH_CLIENT_SECRET=M2UwYzRkNzIwOGQ1OGQ0OWIzMzViYjJjOTEyYTc1
      - ACCOUNT_OAUTH2_REQUEST_KEY=pXf+qkU6P6SAoY2lKW0FtKMS4PylaNA3pY2sUQxNFDk=
      - ACCOUNT_OAUTH2_TOKEN_KEY=8sjqDklsgnwe98htthwAzp==
      - ACCOUNT_URL=http://account.chs-dev
      - API_LOCAL_URL=http://localhost?API_LOCAL_URL
      - CACHE_SERVER=redis:6379
      - CDN_HOST=cdn.chs-dev
      - CHS_API_KEY=MGQ1MGNlYmFkYzkxZTM2MzlkNGVmMzg4ZjgxMmEz
      - CHS_BACKEND_URL=http://localhost?CHS_BACKEND_URL
      - CHS_KAFKA_API_LOCAL_URL=http://localhost?CHS_KAFKA_API_LOCAL_URL
      - CHS_MONITOR_API_LOCAL_URL=http://localhost?CHS_MONITOR_API_LOCAL_URL
      - CHS_MONITOR_GUI_URL=http://localhost?CHS_MONITOR_GUI_URL
      - CHS_URL=http://localhost?CHS_URL
      - COOKIE_DOMAIN=chs-dev
      - COOKIE_SECRET=ChGovUk-XQrbf3sLj2abFxIY2TlapsJ
      - DISABLE_FOLLOW=0
      - DOCUMENT_API_LOCAL_URL=http://localhost?DOCUMENT_API_LOCAL_URL
      - MONGODB_URL=mongodb://mongo
      - PIWIK_URL=
      - PIWIK_SITE_ID=
      - PIWIK_EMBED=
      - QUEUE_API_LOCAL_URL=http://localhost?QUEUE_API_LOCAL_URL
      - STATSD_HOST=localhost
      - STATSD_PORT=8125
      - URL_SIGNING_SALT=F2V3S21sqrxArLn1Pr4B[S6ewO)|21nUD02132ByFrr3YrEgaw7HJhTcGrkEmxJH
    depends_on:
      - mongo
      - redis
    networks:
      - chs-dev
    expose:
      - 4000
  ch-gov-uk:
    container_name: ch-gov-uk
    image: 169942020521.dkr.ecr.eu-west-1.amazonaws.com/local/ch.gov.uk:latest
    labels:
      - traefik.http.routers.ch-gov-uk.rule=Host(`chs-dev`)
    environment:
      - ACCOUNT_URL=http://account.chs-dev
      - ACCOUNT_LOCAL_URL=http://account-ch-gov-uk:4000
      - CACHE_SERVER=redis:6379
      - CDN_HOST=cdn.chs-dev
      - CH_OAUTH2_REQUEST_KEY=pXf+qkU6P6SAoY2lKW0FtKMS4PylaNA3pY2sUQxNFDk=
      - CHS_CH_CLIENT_ID=1234567890.apps.ch.gov.uk
      - CHS_CH_CLIENT_SECRET=M2UwYzRkNzIwOGQ1OGQ0OWIzMzViYjJjOTEyYTc1
      - CHS_URL=http://chs-dev
      - COOKIE_DOMAIN=chs-dev
      - COOKIE_SECRET=ChGovUk-XQrbf3sLj2abFxIY2TlapsJ
      - URL_SIGNING_SALT=F2V3S21sqrxArLn1Pr4B[S6ewO)|21nUD02132ByFrr3YrEgaw7HJhTcGrkEmxJH
    networks:
      - chs-dev
    expose:
      - 2000
  chs-company-profile-api:
    container_name: chs-company-profile-api
    image: 169942020521.dkr.ecr.eu-west-1.amazonaws.com/local/chs-company-profile-api:latest
    labels:
      - traefik.http.routers.account-ch-gov-uk.rule=Host(`chs-company-profile-api`)
    environment:
      - CHS_COMPANY_PROFILE_API_PORT=18222
      - CHS_COMPANY_PROFILE_API_LOCAL_URL=http://wswebdev2.orctel.internal:18222
      - MONGODB_URL=mongodb://mongo
      - API_LOCAL_URL=http://localhost?API_LOCAL_URL
      - COOKIE_SECRET=abcdef123456
    depends_on:
      - mongo
    expose:
      - 18222
    networks:
      - chs-dev
  # Infrastructure
  redis:
    container_name: redis
    image: redis:6-alpine
    networks:
      - chs-dev
    expose:
      - 6379
  mongo:
    container_name: mongo
    image: mongo:4
    environment:
      - MONGO_INITDB_DATABASE=account
    volumes:
      - ./services/infrastructure/mongo.initdb.js:/docker-entrypoint-initdb.d/mongo.initdb.js
    networks:
      - chs-dev
    expose:
      - 27017


networks:
  chs-dev: {}
