version: "3.7"

services:
  app:
    build: .
    image: dissolution-web:1.0
    ports:
      - 3001:3000
    working_dir: /app
    environment:
      CACHE_SERVER: 0.0.0.0:6379
      CACHE_DB: 0
      CACHE_PASSWORD:

      COOKIE_NAME: __SID
      COOKIE_DOMAIN: chs-dev.internal
      COOKIE_SECURE_ONLY: 0
      COOKIE_SECRET: ChGovUk-XQrbf3sLj2abFxIY2TlapsJ
      DEFAULT_SESSION_EXPIRATION: 3600

      ACCOUNT_WEB_URL: http://web.chs-dev.internal:4000

      FILE_TRANSFER_API_URL:
      FILE_TRANSFER_API_KEY:
      MAX_FILE_SIZE_BYTES: 4194304
      SUPPORTED_MIME_TYPES: 'application/pdf,image/jpeg,image/png,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/zip,application/octet-stream,application/x-zip-compressed,application/x-zip,multipart/x-zip,image/gif,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
      MAX_NUMBER_OF_FILES: 10

      FILE_TRANSFER_FEATURE: 1

      KAFKA_BROKER_ADDR: chs-kafka:9092

      SC_TEAM_EMAIL: 'appeals.ch.fake+SC@gmail.com'
      NI_TEAM_EMAIL: 'appeals.ch.fake+NI@gmail.com'
      DEFAULT_TEAM_EMAIL: 'appeals.ch.fake+DEFAULT@gmail.com'

      CDN_HOST: assets

      APPEALS_API_URL: http://api.chs-dev.internal

      LOG_LEVEL: info
      HUMAN_LOG: 1
