version: "3.8"

services:
  ingress-proxy:
    container_name: dissolution-ingress-proxy
    image: traefik:v2.2
    command: --api.insecure=true --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
    networks:
      - chs-dev
    ports:
      - 80:80
      - 8080:8080 # Web UI (enabled by --api.insecure=true)
  dissolution-web:
    build: .
    container_name: dissolution-web
    image: dissolution-web:1.0
    labels:
      - traefik.http.routers.dissolution-web.rule=Host(`chs-dev`) && PathPrefix(`/close-a-company/`)
    ports:
      - 3000:3000
    networks:
      - chs-dev
    working_dir: /app
    environment:
      - ACCOUNT_URL=http://account.chs-dev
      - API_URL=http://api-ch-gov-uk:18001
      - CHS_URL=http://chs-dev
      - CDN_HOST=cdn.chs-dev
      - CHS_COMPANY_PROFILE_API_LOCAL_URL=http://chs-company-profile-api:3054
      - CACHE_SERVER=redis
      - CACHE_DB=0
      - CACHE_PASSWORD=''
      - COOKIE_NAME=__SID
      - COOKIE_DOMAIN=chs-dev
      - COOKIE_SECURE_ONLY=0
      - COOKIE_SECRET=ChGovUk-XQrbf3sLj2abFxIY2TlapsJ
      - DEFAULT_SESSION_EXPIRATION=3600
      - DISSOLUTIONS_API_URL=http://eric:4001
      - LOG_LEVEL=info
      - HUMAN_LOG=1
      - OAUTH2_CLIENT_ID=1234567890.apps.ch.gov.uk
      - OAUTH2_REQUEST_KEY=pXf+qkU6P6SAoY2lKW0FtKMS4PylaNA3pY2sUQxNFDk=
    depends_on:
      - mongo
      - cdn-ch-gov-uk
      - account-ch-gov-uk
      - ch-gov-uk
      - chs-company-profile-api
      - dissolution-api
  dissolution-api:
    build: ../dissolution-api/.
    container_name: dissolution-api
    labels:
      - traefik.http.routers.dissolution-api.rule=Host(`chs-dev`) && PathPrefix(`/dissolution-api/`)
    environment:
      - DISSOLUTIONS_API_MONGODB_URL=mongodb://mongo/dissolutions
      - CDN_HOST=cdn.chs-dev
      - CACHE_SERVER=redis
      - CACHE_DB=0
      - CACHE_PASSWORD=''
      - COOKIE_NAME=__SID
      - COOKIE_DOMAIN=chs-dev
      - COOKIE_SECURE_ONLY=0
      - COOKIE_SECRET=ChGovUk-XQrbf3sLj2abFxIY2TlapsJ
      - DEFAULT_SESSION_EXPIRATION=3600
    ports:
      - 3001:3001
    expose:
      - 3001
    networks:
      - chs-dev
    working_dir: /app
  # Integrations
  cdn-ch-gov-uk:
    container_name: cdn-ch-gov-uk
    image: 169942020521.dkr.ecr.eu-west-1.amazonaws.com/local/cdn.ch.gov.uk:latest
    labels:
      - traefik.http.routers.cdn-ch-gov-uk.rule=Host(`cdn.chs-dev`)
    networks:
      - chs-dev
    expose:
      - 80
  account-ch-gov-uk:
    container_name: account-ch-gov-uk
    image: 169942020521.dkr.ecr.eu-west-1.amazonaws.com/local/account.ch.gov.uk:latest
    labels:
      - traefik.http.routers.account-ch-gov-uk.rule=Host(`account.chs-dev`)
    environment:
      - ACCOUNT_CH_CLIENT_ID=1234567890.apps.ch.gov.uk
      - ACCOUNT_CH_CLIENT_SECRET=M2UwYzRkNzIwOGQ1OGQ0OWIzMzViYjJjOTEyYTc1
      - ACCOUNT_OAUTH2_REQUEST_KEY=pXf+qkU6P6SAoY2lKW0FtKMS4PylaNA3pY2sUQxNFDk=
      - ACCOUNT_OAUTH2_TOKEN_KEY=8sjqDklsgnwe98htthwAzp==
      - ACCOUNT_URL=http://account.chs-dev
      - API_LOCAL_URL=http://chs-company-profile-api:3054
      - CACHE_SERVER=redis:6379
      - CDN_HOST=cdn.chs-dev
      - CHS_API_KEY=MGQ1MGNlYmFkYzkxZTM2MzlkNGVmMzg4ZjgxMmEz
      - CHS_BACKEND_URL=http://localhost?CHS_BACKEND_URL
      - CHS_KAFKA_API_LOCAL_URL=http://localhost?CHS_KAFKA_API_LOCAL_URL
      - CHS_MONITOR_API_LOCAL_URL=http://localhost?CHS_MONITOR_API_LOCAL_URL
      - CHS_MONITOR_GUI_URL=http://localhost?CHS_MONITOR_GUI_URL
      - CHS_URL=http://chs-dev
      - COOKIE_DOMAIN=chs-dev
      - COOKIE_SECRET=ChGovUk-XQrbf3sLj2abFxIY2TlapsJ
      - DISABLE_FOLLOW=0
      - DOCUMENT_API_LOCAL_URL=http://localhost?DOCUMENT_API_LOCAL_URL
      - MONGODB_URL=mongodb://mongo
      - PIWIK_URL=
      - PIWIK_SITE_ID=
      - PIWIK_EMBED=
      - QUEUE_API_LOCAL_URL=http://localhost?QUEUE_API_LOCAL_URL
      - STATSD_HOST=localhost
      - STATSD_PORT=8125
      - URL_SIGNING_SALT=F2V3S21sqrxArLn1Pr4B[S6ewO)|21nUD02132ByFrr3YrEgaw7HJhTcGrkEmxJH
    depends_on:
      - mongo
      - redis
    networks:
      - chs-dev
    expose:
      - 4000
  ch-gov-uk:
    container_name: ch-gov-uk
    image: 169942020521.dkr.ecr.eu-west-1.amazonaws.com/local/ch.gov.uk:latest
    labels:
      - traefik.http.routers.ch-gov-uk.rule=Host(`chs-dev`)
    environment:
      - ACCOUNT_URL=http://account.chs-dev
      - ACCOUNT_LOCAL_URL=http://account-ch-gov-uk:4000
      - CACHE_SERVER=redis:6379
      - CDN_HOST=cdn.chs-dev
      - CH_OAUTH2_REQUEST_KEY=pXf+qkU6P6SAoY2lKW0FtKMS4PylaNA3pY2sUQxNFDk=
      - CHS_CH_CLIENT_ID=1234567890.apps.ch.gov.uk
      - CHS_CH_CLIENT_SECRET=M2UwYzRkNzIwOGQ1OGQ0OWIzMzViYjJjOTEyYTc1
      - CHS_URL=http://chs-dev
      - COOKIE_DOMAIN=chs-dev
      - COOKIE_SECRET=ChGovUk-XQrbf3sLj2abFxIY2TlapsJ
      - URL_SIGNING_SALT=F2V3S21sqrxArLn1Pr4B[S6ewO)|21nUD02132ByFrr3YrEgaw7HJhTcGrkEmxJH
    networks:
      - chs-dev
    expose:
      - 2000
  eric:
    container_name: chs-eric
    image: 169942020521.dkr.ecr.eu-west-1.amazonaws.com/local/eric:latest
    environment:
      - ACCOUNT_API_URL=http://account-ch-gov-uk:4000
      - AES256_KEY=lwmso88WvX5Nubs3QWkq45YZq3W6gx8jregjeOKTqnc=
      - API_KEY=MGQ1MGNlYmFkYzkxZTM2MzlkNGVmMzg4ZjgxMmEz
      - CACHE_URL=redis:6379
      - DEVELOPER_HUB_URL=http://localhost?DEVELOPER_HUB_URL
      - PROXY_TARGET_URLS=http://payments-api:3055
    networks:
      - chs-dev
    expose:
      - 4001
  chs-company-profile-api:
    container_name: chs-company-profile-api
    image: 169942020521.dkr.ecr.eu-west-1.amazonaws.com/local/chs-company-profile-api:latest
    labels:
      - traefik.http.routers.chs-company-profile-api.rule=Host(`chs-company-profile-api`)
    environment:
      - COOKIE_SECRET=ChGovUk-XQrbf3sLj2abFxIY2TlapsJ
      - PERL5LIB=local/lib/perl5
      - PORT=3054
      - MONGODB_URL=mongodb://mongo
    depends_on:
      - mongo
    expose:
      - 3054
    networks:
      - chs-dev
  api-ch-gov-uk:
    image: 169942020521.dkr.ecr.eu-west-1.amazonaws.com/local/api.ch.gov.uk:latest
    container_name: api-ch-gov-uk
    labels:
      - traefik.http.routers.api-ch-gov-uk.rule=Host(`api.chs-dev`)
    environment:
      - CUSTOMER_FEEDBACK_EMAIL_ADDRESS=kochab@companieshouse.gov.uk
      - ELASTIC_SEARCH_VERSION=5
      - SHARED_MEMORY_PERCENTAGE=25
      - MAX_MEMORY_USAGE=262144
      - COOKIE_DOMAIN=chs-dev
      - COOKIE_SECRET=ChGovUk-XQrbf3sLj2abFxIY2TlapsJ
      - ELASTIC_SEARCH_ALL_INDEX=primary_search
      - ELASTIC_SEARCH_PRIMARY_INDEX=primary_search
      - MONGODB_URL=mongodb://mongo
    ports:
      - 18001:18001
    networks:
      - chs-dev
    working_dir: /app
  payments-api:
    container_name: payments-api
    image: 169942020521.dkr.ecr.eu-west-1.amazonaws.com/local/payments.api.ch.gov.uk:latest
    labels:
      - traefik.http.routers.payments-api.rule=Host(`payments-api`)
    ports:
      - 3055:80
    expose:
      - 3055
    networks:
      - chs-dev
    working_dir: /app
    environment:
      - MONGODB_URL=mongodb://mongo
      - MONGODB_DATABASE=payments
      - MONGODB_COLLECTION=payments
      - GOV_PAY_URL=http://payments-web
      - DOMAIN_WHITELIST=http://dissolution-api:3001
  payments-web:
    container_name: payments-web
    image: 169942020521.dkr.ecr.eu-west-1.amazonaws.com/local/payments.web.ch.gov.uk:latest
    labels:
      - traefik.http.routers.payments-web.rule=Host(`payments-web`)
    ports:
      - 3056:3056
    expose:
      - 3056
    networks:
      - chs-dev
    environment:
      - API_URL=http://payments-api
      - CACHE_POOL_SIZE=1
      - CACHE_SERVER=redis
      - COOKIE_NAME=__SID
      - COOKIE_DOMAIN=chs-dev
      - COOKIE_SECRET=ChGovUk-XQrbf3sLj2abFxIY2TlapsJ
      - DEFAULT_SESSION_EXPIRATION=500000000
      - OAUTH2_AUTH_URI=http://account.chs-dev/oauth2/authorise
      - OAUTH2_CLIENT_ID=1234567890.apps.ch.gov.uk
      - OAUTH2_REDIRECT_URI=http://chs-dev/oauth2/user/callback
      - OAUTH2_REQUEST_KEY=pXf+qkU6P6SAoY2lKW0FtKMS4PylaNA3pY2sUQxNFDk=
  # Infrastructure
  redis:
    container_name: redis
    image: redis:6-alpine
    networks:
      - chs-dev
    expose:
      - 6379
  mongo:
    container_name: mongo
    image: mongo:4
    environment:
      - MONGO_INITDB_DATABASE=account
    volumes:
      - ./services/infrastructure/mongo.initdb.js:/docker-entrypoint-initdb.d/mongo.initdb.js
    networks:
      - chs-dev
    expose:
      - 27017
    ports:
      - 27017:27017


networks:
  chs-dev: {}
