version: "3.8"

services:
  ingress-proxy:
    container_name: chs-ingress-proxy
    image: traefik:v2.2
    command: --api.insecure=true --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
    networks:
      - chs-dev
    ports:
      - 80:80
      - 8080:8080 # Web UI (enabled by --api.insecure=true)

networks:
  chs-dev: {}
