import 'app/controllers/form.controller'
import 'app/controllers/healthcheck.controller'
import 'app/controllers/landing.controller'
import 'app/controllers/searchCompany.controller'
import 'app/controllers/selectDirector.controller'
import 'app/controllers/whoToTell.controller'
//import 'app/controllers/viewCompanyInformation.controller'
